import os
import shutil
from pathlib import Path

from flask_frozen import Freezer
from app import app


def main():
    app.config['FREEZER_DESTINATION'] = '../build'
    freezer = Freezer(app)
    freezer.freeze()
    github_repository = os.getenv('GITHUB_REPOSITORY')
    if github_repository:
        # A prefix will be generated by the flask app, but we don't want to have that path as a directory,
        # since github will prefix username.github.io/repositoryname automatically.
        # Therefore, move the stuff out of the inner directory
        owner, sep, repo = github_repository.partition('/')
        directory = Path(freezer.root) / repo
        tmp_path = Path('/tmp/tmp_build_dir')
        directory.rename(tmp_path)
        shutil.rmtree(freezer.root)
        tmp_path.rename(freezer.root)


if __name__ == '__main__':
    main()
