name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: 'ubuntu-18.04'

    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: x64
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: pipenv sync
    - name: Run stylecheck
      run: pipenv run flake8 .
    - name: Run tests
      run: GITHUB_REPOSITORY="" pipenv run nosetests --with-doctest .

  deploy:
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: x64
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: pipenv sync
    - name: Build static version
      run: pipenv run src/freeze.py
    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --global user.name "$GITHUB_ACTOR"
        export REMOTE=$(git config remote.origin.url)
        git checkout --orphan gh-pages
        rsync -a \
          --filter='P build' \
          --filter='P .git/' \
          --delete-excluded \
          build/ .
        rm -rf build/
        git add -A
        git commit -m "GitHub Actions build $(date -Iseconds)"
        git push -fq "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" gh-pages
